name: DevBuild

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      
      - name: npm ci
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          CF_SPACE_ID: ${{ secrets.CF_SPACE_ID }}
          CF_ACCESS_TOKEN: ${{ secrets.CF_ACCESS_TOKEN }}
          