name: Build Blog and Deploy to Netlify

on:
  repository_dispatch:
    types: [build]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm install
      - run: npm run build
        env:
          CF_SPACE_ID: ${{ secrets.CF_SPACE_ID }}
          CF_ACCESS_TOKEN: ${{ secrets.CF_ACCESS_TOKEN }}

      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
